// <auto-generated />
using System;
using DicomLearning.GraphQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DicomLearning.GraphQL.Migrations
{
    [DbContext(typeof(DicomDbContext))]
    [Migration("20260711053201_AddOrderColumn")]
    partial class AddOrderColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("UserStudyId");

                    b.ToTable("user_series", (string)null);
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserSop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserSeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("Order");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("UserSeriesId");

                    b.ToTable("user_sop", (string)null);
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPartExamined")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("Order");

                    b.HasIndex("PatientId");

                    b.HasIndex("StudyDate");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.HasIndex("PatientId", "StudyDate");

                    b.ToTable("user_study", (string)null);
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserSeries", b =>
                {
                    b.HasOne("DicomLearning.GraphQL.Models.UserStudy", "Study")
                        .WithMany("Series")
                        .HasForeignKey("UserStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserSop", b =>
                {
                    b.HasOne("DicomLearning.GraphQL.Models.UserSeries", "Series")
                        .WithMany("Sops")
                        .HasForeignKey("UserSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserSeries", b =>
                {
                    b.Navigation("Sops");
                });

            modelBuilder.Entity("DicomLearning.GraphQL.Models.UserStudy", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
